name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dyalog/dyalog:20.0
      options: --user root

    steps:
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y git nodejs zip unzip

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Activate Tatin and Cider
        run: dyalogscript .github/activate.apls
        
      - name: Build package
        run: dyalogscript Build.apls

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stark
          path: Dist/dyalog_labs-Stark-*.zip
