name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: dyalog/dyalog:20.0

    steps:
      - name: Checkout
        run: |
          git clone --depth 1 --branch ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} https://github.com/$GITHUB_REPOSITORY.git .

      - name: Run tests
        run: cd Tests && dyalogscript RunTests.apls
